import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from numpy import random
df=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\mine\\test data 1.csv" )
print(df.head(30))
df.dropna(inplace=True)
print(df.head(30))
print(df.info())
print(df.columns)
df[" PRICE "]=df[" PRICE "].str.replace("$","", regex=False).astype(float)
print(df.info())
print(df.corr(numeric_only=True))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.show()
first5 = df.head(5)
sns.displot(random.normal(size=30), kde=True)
plt.xlabel(" PRICE ")
plt.ylabel("Frequency")
plt.title("Distribution of Prices for the Hairstyles")
plt.show()
plt.scatter(first5["HAIRSTYLE"], first5[" PRICE "])
plt.xlabel("HAIRSTYLE")
plt.ylabel(" PRICE ")
plt.title("Price of the first 5 hairstyles")
plt.show()
sns.displot(random.poisson(lam=2, size=30), kde=True)
plt.xlabel(" PRICE ")
plt.ylabel("Frequency")
plt.title("Distribution of Prices for the Hairstyles")
plt.show()
